-- apply_all.sql — generated concatenation of supabase/migrations/*.sql, in order.
-- Run in the Supabase SQL editor. If a previous run failed part-way, run supabase/reset.sql FIRST.
-- Do NOT edit this file by hand. Regenerate after editing any migration.

-- ==================== supabase/migrations/0001_schema.sql ====================
-- 0001_schema.sql — the frozen data model.
-- STATUS: written, NOT applied. No Supabase secret key / CLI was available in this session
-- (see docs/RELEASE-SCOPE.md §6). It is the source of truth for the table shapes mirrored in
-- lib/types.ts. Apply with `supabase db push` once the secret key exists, then run the test suite.

create extension if not exists pg_trgm;
create extension if not exists pgcrypto;

create type requirement_status as enum
  ('received','qualifying','quoted','submitted','won','lost','cancelled');
create type commitment_kind as enum ('firm','indicative');
create type oem_approval_status as enum ('approved','conditional','not_approved');
create type quote_status as enum ('draft','pending_approval','approved','rejected','superseded');
create type loss_reason as enum
  ('price','technical_non_compliance','delivery_timeline','competitor_preference',
   'quantity_or_capacity','cancelled','not_pursued','other');
create type app_role as enum ('owner','sales','operations','finance');
create type document_type as enum
  ('quotation','invoice','compliance_certificate','technical_drawing','pdi_report','other');
create type coverage_state as enum ('covered','partly_covered','no_cover');
create type approval_status as enum ('requested','approved','rejected');

-- One app profile per auth user, carrying the four-role claim.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role app_role not null default 'sales',
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.requirements (
  id uuid primary key default gen_random_uuid(),
  ref text not null unique,
  customer text not null,
  status requirement_status not null default 'received',
  submission_deadline date not null,
  loss_reason loss_reason,
  notes text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  constraint lost_needs_reason check (status <> 'lost' or loss_reason is not null)
);

create table public.requirement_lines (
  id uuid primary key default gen_random_uuid(),
  requirement_id uuid not null references public.requirements(id) on delete cascade,
  line_no integer not null,
  part_number text not null,
  description text not null default '',
  quantity integer not null check (quantity > 0),
  uom text not null,
  deadline date not null,
  is_demo boolean not null default false,
  unique (requirement_id, line_no)
  -- deadline >= requirement.submission_deadline is enforced by trigger in 0003, because
  -- Postgres does not allow a subquery inside a CHECK constraint.
);

create table public.oems (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  approval_status oem_approval_status not null default 'not_approved',
  lead_time_days integer not null default 0 check (lead_time_days >= 0),
  capabilities text[] not null default '{}',
  contact_name text,
  contact_email text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.oem_products (
  id uuid primary key default gen_random_uuid(),
  oem_id uuid not null references public.oems(id) on delete cascade,
  part_number text not null,
  description text not null default '',
  unit_price numeric(14,2) not null check (unit_price >= 0),
  currency char(3) not null default 'INR',
  lead_time_days integer not null default 0 check (lead_time_days >= 0),
  is_demo boolean not null default false,
  unique (oem_id, part_number)
);

-- Firm and indicative are separate facts. Nothing in the schema lets them be summed together.
create table public.commitments (
  id uuid primary key default gen_random_uuid(),
  requirement_line_id uuid not null references public.requirement_lines(id) on delete cascade,
  oem_id uuid not null references public.oems(id),
  kind commitment_kind not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(14,2) not null check (unit_price >= 0),
  expected_date date not null,
  shipment_seq integer not null default 1 check (shipment_seq > 0),
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  unique (requirement_line_id, oem_id, shipment_seq)
);

create table public.oem_requests (
  id uuid primary key default gen_random_uuid(),
  requirement_line_id uuid not null references public.requirement_lines(id) on delete cascade,
  oem_id uuid not null references public.oems(id),
  requested_at timestamptz not null default now(),
  responded_at timestamptz,
  response_notes text,
  is_demo boolean not null default false,
  unique (requirement_line_id, oem_id)
);

create table public.quotes (
  id uuid primary key default gen_random_uuid(),
  requirement_id uuid not null references public.requirements(id) on delete cascade,
  status quote_status not null default 'draft',
  current_version integer not null default 1 check (current_version > 0),
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.quote_versions (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  version_no integer not null check (version_no > 0),
  status quote_status not null default 'draft',
  approved_at timestamptz,
  is_demo boolean not null default false,
  unique (quote_id, version_no)
);

create table public.quote_version_lines (
  id uuid primary key default gen_random_uuid(),
  quote_version_id uuid not null references public.quote_versions(id) on delete cascade,
  requirement_line_id uuid not null references public.requirement_lines(id),
  oem_price numeric(14,2) not null check (oem_price >= 0),
  lead_time_days integer not null default 0 check (lead_time_days >= 0),
  target_margin_pct numeric(6,2) not null default 15,
  final_price numeric(14,2) check (final_price is null or final_price >= 0),
  is_demo boolean not null default false,
  unique (quote_version_id, requirement_line_id)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id),
  requirement_id uuid not null references public.requirements(id),
  po_ref text,
  supplier_po_ref text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.order_stages (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  stage text not null,
  owner text,
  expected_date date,
  committed_date date,
  completed_at timestamptz,
  is_demo boolean not null default false
);

create table public.pdi_records (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  offered_qty integer not null default 0 check (offered_qty >= 0),
  cleared_qty integer not null default 0 check (cleared_qty >= 0),
  rejected_qty integer not null default 0 check (rejected_qty >= 0),
  held boolean not null default false,
  is_demo boolean not null default false,
  constraint pdi_split check (cleared_qty + rejected_qty <= offered_qty)
);

create table public.deliveries (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  delivered_on date not null,
  is_demo boolean not null default false
);

create table public.oem_invoices (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  invoice_no text not null,
  gross_amount numeric(14,2) not null default 0 check (gross_amount >= 0),
  due_date date,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  oem_invoice_id uuid not null references public.oem_invoices(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  paid_on date not null,
  kind text not null default 'customer_receipt',
  is_demo boolean not null default false
);

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  type document_type not null,
  owner_type text not null check (owner_type in ('requirement','oem','order')),
  owner_id uuid not null,
  title text not null,
  issue_date date,
  expiry_date date,
  storage_path text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  title text not null,
  owner_type text,
  owner_id uuid,
  due_date date,
  completed_at timestamptz,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.approvals (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null,
  entity_id uuid not null,
  status approval_status not null default 'requested',
  actor uuid references auth.users(id),
  reason text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.audit_log (
  id bigint generated always as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  before jsonb,
  after jsonb,
  actor uuid,
  at timestamptz not null default now()
);

create index requirement_lines_requirement_idx on public.requirement_lines(requirement_id);
create index commitments_line_idx on public.commitments(requirement_line_id);
create index commitments_kind_idx on public.commitments(kind);
create index oem_requests_line_idx on public.oem_requests(requirement_line_id);
create index documents_expiry_idx on public.documents(expiry_date);

-- ==================== supabase/migrations/0002_views.sql ====================
-- 0002_views.sql — the single source of truth for coverage and pricing.
-- STATUS: written, NOT applied.
-- Every view is security_invoker so the querying user's RLS applies (docs/TECH-STACK.md).

create or replace view public.requirement_line_coverage
with (security_invoker = true) as
with firm as (
  select requirement_line_id, sum(quantity)::int as qty
  from public.commitments where kind = 'firm'
  group by requirement_line_id
),
ind as (
  select requirement_line_id, sum(quantity)::int as qty
  from public.commitments where kind = 'indicative'
  group by requirement_line_id
)
select
  l.id as requirement_line_id,
  l.quantity as required_qty,
  coalesce(f.qty, 0) as firm_committed_qty,
  coalesce(i.qty, 0) as indicative_qty,
  greatest(l.quantity - coalesce(f.qty, 0), 0) as uncovered_qty,
  greatest(coalesce(f.qty, 0) - l.quantity, 0) as over_committed_qty,
  case
    when l.quantity - coalesce(f.qty, 0) <= 0 then 'covered'::coverage_state
    when coalesce(f.qty, 0) > 0 then 'partly_covered'::coverage_state
    else 'no_cover'::coverage_state
  end as state
from public.requirement_lines l
left join firm f on f.requirement_line_id = l.id
left join ind i on i.requirement_line_id = l.id;

create or replace view public.requirement_line_firm_by_oem
with (security_invoker = true) as
select requirement_line_id, oem_id, sum(quantity)::int as quantity
from public.commitments
where kind = 'firm'
group by requirement_line_id, oem_id;

-- Recommended price is ADVISORY and derived only from OEM price + target margin.
-- final_price is never written by this function; it stays a human field.
create or replace function public.recommended_price(oem_price numeric, margin_pct numeric)
returns numeric
language sql
immutable
as $$
  select round(oem_price * (1 + margin_pct / 100.0), 2)
$$;

-- ==================== supabase/migrations/0003_audit.sql ====================
-- 0003_audit.sql — append-only audit trail + the deadline guard.
-- STATUS: written, NOT applied.
-- The audit function is SECURITY DEFINER so a signed-in user can write an audit row without
-- holding INSERT rights on audit_log. actor is always auth.uid(); no app code supplies it.

create or replace function public.write_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_id text;
begin
  row_id := coalesce(
    (to_jsonb(new) ->> 'id'),
    (to_jsonb(old) ->> 'id')
  );
  insert into public.audit_log(entity_type, entity_id, action, before, after, actor)
  values (
    tg_table_name,
    row_id,
    lower(tg_op),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end,
    auth.uid()
  );
  return coalesce(new, old);
end;
$$;

-- Attach the trigger to every material table. Extend this list as tables are added.
do $$
declare
  t text;
begin
  foreach t in array array[
    'requirements','requirement_lines','oems','oem_products','commitments','oem_requests',
    'quotes','quote_versions','quote_version_lines','orders','order_stages','pdi_records',
    'deliveries','oem_invoices','payments','documents','approvals'
  ] loop
    execute format(
      'create trigger audit_%1$s after insert or update or delete on public.%1$I
       for each row execute function public.write_audit()', t);
  end loop;
end $$;

-- deadline >= requirement.submission_deadline (Postgres forbids a subquery in CHECK).
create or replace function public.check_line_deadline()
returns trigger
language plpgsql
as $$
declare
  sub date;
begin
  select submission_deadline into sub
  from public.requirements where id = new.requirement_id;
  if new.deadline < sub then
    raise exception 'Line deadline % is before submission deadline %', new.deadline, sub;
  end if;
  return new;
end;
$$;

create trigger requirement_lines_deadline
  before insert or update on public.requirement_lines
  for each row execute function public.check_line_deadline();

-- ==================== supabase/migrations/0004_rls.sql ====================
-- 0004_rls.sql — Row-Level Security: the authorization boundary.
-- STATUS: written, NOT applied. This is the highest-consequence file in the repo.
-- With a public anon key, RLS is the authorization. A table with RLS enabled and no matching
-- policy returns zero rows (default deny). Every table must be listed below.

alter table public.profiles            enable row level security;
alter table public.requirements        enable row level security;
alter table public.requirement_lines   enable row level security;
alter table public.oems                enable row level security;
alter table public.oem_products        enable row level security;
alter table public.commitments         enable row level security;
alter table public.oem_requests        enable row level security;
alter table public.quotes              enable row level security;
alter table public.quote_versions      enable row level security;
alter table public.quote_version_lines enable row level security;
alter table public.orders              enable row level security;
alter table public.order_stages        enable row level security;
alter table public.pdi_records         enable row level security;
alter table public.deliveries          enable row level security;
alter table public.oem_invoices        enable row level security;
alter table public.payments            enable row level security;
alter table public.documents           enable row level security;
alter table public.tasks               enable row level security;
alter table public.approvals           enable row level security;
alter table public.audit_log           enable row level security;

-- The caller's role, read without recursive RLS.
create or replace function public.current_app_role()
returns app_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
as $$ select public.current_app_role() = 'owner' $$;

-- Profiles: a user sees their own row; owner sees all.
create policy profiles_self_read on public.profiles
  for select using (id = auth.uid() or public.is_owner());
create policy profiles_owner_write on public.profiles
  for all using (public.is_owner()) with check (public.is_owner());

-- Owner/management: full access to every material table.
do $$
declare
  t text;
begin
  foreach t in array array[
    'requirements','requirement_lines','oems','oem_products','commitments','oem_requests',
    'quotes','quote_versions','quote_version_lines','orders','order_stages','pdi_records',
    'deliveries','oem_invoices','payments','documents','tasks','approvals'
  ] loop
    execute format(
      'create policy owner_all on public.%1$I for all
       using (public.is_owner()) with check (public.is_owner())', t);
  end loop;
end $$;

-- Sales: the front of the funnel. No access to payments.
do $$
declare
  t text;
begin
  foreach t in array array[
    'requirements','requirement_lines','oems','oem_products','commitments','oem_requests',
    'quotes','quote_versions','quote_version_lines','documents','tasks'
  ] loop
    execute format(
      'create policy sales_rw on public.%1$I for all
       using (public.current_app_role() = ''sales'')
       with check (public.current_app_role() = ''sales'')', t);
  end loop;
end $$;

-- Operations: fulfilment. May read requirements and write order/PDI/delivery/documents.
do $$
declare
  t text;
begin
  foreach t in array array[
    'orders','order_stages','pdi_records','deliveries','documents','tasks','oems'
  ] loop
    execute format(
      'create policy ops_rw on public.%1$I for all
       using (public.current_app_role() = ''operations'')
       with check (public.current_app_role() = ''operations'')', t);
  end loop;
end $$;
create policy ops_read_requirements on public.requirements
  for select using (public.current_app_role() = 'operations');

-- Finance: invoices, payments, documents, and read of orders.
do $$
declare
  t text;
begin
  foreach t in array array['oem_invoices','payments','documents','tasks'] loop
    execute format(
      'create policy finance_rw on public.%1$I for all
       using (public.current_app_role() = ''finance'')
       with check (public.current_app_role() = ''finance'')', t);
  end loop;
end $$;
create policy finance_read_orders on public.orders
  for select using (public.current_app_role() = 'finance');

-- Audit: owner may read; nobody may write except the SECURITY DEFINER trigger (no INSERT/
-- UPDATE/DELETE policy is created, so the table is append-only through the trigger alone).
create policy audit_owner_read on public.audit_log
  for select using (public.is_owner());

-- ==================== supabase/migrations/0005_extended_modules.sql ====================
-- 0005_extended_modules.sql — close the gaps between the Odoo "Input Sheet" and the schema.
-- STATUS: written, NOT applied (no Supabase secret key / CLI in this session — see REPORT.md).
-- Source of the field list: docs/DATA-MAP.md, from Inverbrass Odoo Order Management sheet (1).
-- This extends the Phase-1 model with the modules the client's sheet defines but the plan's
-- original table list did not enumerate. It does not change any screen by itself.

-- ---------------------------------------------------------------------------
-- Master data
-- ---------------------------------------------------------------------------

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  division text,
  sub_division text,
  billing_address text,
  delivery_address text,
  gst_number text,
  gem_registration text,
  vendor_registration text,
  portal_login_mapping text,
  payment_terms text,
  approval_requirements text[] not null default '{}',
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.customer_contacts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  is_demo boolean not null default false
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  part_number text not null,
  client_part_number text,
  description text not null default '',
  hsn_code text,
  uom text not null default 'nos',
  category text,
  technical_specifications text,
  compliance_certifications text[] not null default '{}', -- RCMA, CEMILAC, DGQA, LCSO, MIL
  standard_price numeric(14,2),
  currency char(3) not null default 'INR',
  lead_time_days integer check (lead_time_days >= 0),
  moq integer check (moq >= 0),
  shelf_life_days integer,
  export_restriction text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  unique (part_number, client_part_number)
);

create table public.product_oems (
  product_id uuid not null references public.products(id) on delete cascade,
  oem_id uuid not null references public.oems(id) on delete cascade,
  primary key (product_id, oem_id)
);

alter table public.oems
  add column brand_category text,
  add column country_of_origin text,
  add column product_portfolio text,
  add column moq_rules text,
  add column pricing_validity text,
  add column freight_terms text,
  add column warranty_terms text,
  add column payment_terms text,
  add column commission_pct numeric(6,2),
  add column nda_status text,
  add column bank_details text;

-- ---------------------------------------------------------------------------
-- RFI / Quotation extensions
-- ---------------------------------------------------------------------------

alter table public.requirements
  add column customer_id uuid references public.customers(id),
  add column project_name text,
  add column bid_type text check (bid_type in ('single','double')),
  add column submission_type text check (submission_type in ('hard','soft','both')),
  add column source text check (source in ('gem','client_portal','direct','oem')),
  add column gem_tender_no text,
  add column quotation_validity_days integer,
  add column assigned_to uuid references auth.users(id),
  add column regret_letter_date date,
  add column competitor_note text;

alter table public.requirement_lines
  add column client_part_number text,
  add column oem_id uuid references public.oems(id),
  add column staggered boolean not null default false,
  add column approval_requirements text[] not null default '{}';

alter table public.quotes add column quote_no text unique;

alter table public.quote_versions
  add column valid_until date,
  add column notes text,
  add column created_at timestamptz not null default now();

alter table public.quote_version_lines
  add column oem_id uuid references public.oems(id),
  add column currency char(3) not null default 'INR',
  add column freight numeric(14,2) not null default 0,
  add column taxes numeric(14,2) not null default 0,
  add column delivery_terms text,
  add column payment_terms text,
  add column discount numeric(14,2) not null default 0,
  add column pnc_status text,
  add column tech_compliant boolean,
  add column comm_compliant boolean;

-- ---------------------------------------------------------------------------
-- Purchase Order, readiness, PDI, delivery
-- ---------------------------------------------------------------------------

alter table public.orders
  add column po_number text unique,
  add column po_date date,
  add column po_value numeric(14,2),
  add column taxes numeric(14,2),
  add column material_readiness_required boolean not null default false,
  add column partial_allowed boolean not null default true,
  add column pdi_required boolean not null default false,
  add column pdi_mode text check (pdi_mode in ('vc','physical')),
  add column pdi_inspector_oem text,
  add column pdi_inspector_client text,
  add column docs_required text,
  add column special_conditions text,
  add column warranty_terms text,
  add column payment_terms text,
  add column status text not null default 'open' check (status in ('open','processing','completed'));
-- (is_demo already exists on orders from 0001 — not added again.)

-- "No orphan PO": a PO may only exist against an APPROVED quote. quote_id is already NOT NULL,
-- so the rule that needs enforcing is the quote's status, which a CHECK cannot see.
create or replace function public.check_order_quote_approved()
returns trigger
language plpgsql
as $$
declare
  q public.quote_status;
begin
  select status into q from public.quotes where id = new.quote_id;
  if q is distinct from 'approved' then
    raise exception 'Order requires an approved quote; quote % is %', new.quote_id, coalesce(q::text, 'missing');
  end if;
  return new;
end;
$$;

create trigger order_requires_approved_quote
  before insert or update on public.orders
  for each row execute function public.check_order_quote_approved();

create table public.order_lines (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  requirement_line_id uuid references public.requirement_lines(id),
  part_number text not null,
  quantity_ordered integer not null check (quantity_ordered > 0),
  unit_price numeric(14,2) not null check (unit_price >= 0),
  delivery_schedule date,
  is_demo boolean not null default false
);

create table public.material_readiness (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  oem_id uuid not null references public.oems(id),
  part_number text not null,
  quantity_ready integer not null default 0 check (quantity_ready >= 0),
  manufacturing_status text not null default 'in_production'
    check (manufacturing_status in ('in_production','ready')),
  internal_qc_status text not null default 'pending'
    check (internal_qc_status in ('pending','approved')),
  batch_number text,
  serial_numbers text,
  tentative_pdi_date date,
  remarks text,
  is_demo boolean not null default false
);

alter table public.pdi_records
  add column part_number text,
  add column oem_id uuid references public.oems(id),
  add column customer_id uuid references public.customers(id),
  add column inspection_type text check (inspection_type in ('physical','vc','third_party')),
  add column agency text,
  add column inspection_date date,
  add column inspector text,
  add column rejection_reason text,
  add column re_pdi_required boolean not null default false,
  add column status text not null default 'pending'
    check (status in ('pending','passed','failed')),
  add column dispatch_clearance text not null default 'hold'
    check (dispatch_clearance in ('approved','hold'));

alter table public.oem_invoices
  add column invoice_date date,
  add column pdi_id uuid references public.pdi_records(id),
  add column customer_id uuid references public.customers(id),
  add column oem_id uuid references public.oems(id),
  add column part_number text,
  add column quantity_invoiced integer,
  add column invoice_type text check (invoice_type in ('full','partial')),
  add column balance_qty integer,
  add column net_amount numeric(14,2),
  add column gst_amount numeric(14,2),
  add column dispatch_date date,
  add column lr_awb text,
  add column courier text,
  add column eway_bill text,
  add column documents_submitted text,
  add column multiple_against_po boolean not null default false,
  add column status text not null default 'raised'
    check (status in ('raised','submitted','approved','paid'));

alter table public.payments
  add column payment_ref text,
  add column payment_terms text,
  add column mode text check (mode in ('rtgs','neft','wire','other')),
  add column proof_path text,
  add column followup_status text not null default 'pending'
    check (followup_status in ('pending','escalated','closed'));

alter table public.deliveries
  add column delivery_ref text,
  add column oem_invoice_id uuid references public.oem_invoices(id),
  add column location text,
  add column status text not null default 'in_transit'
    check (status in ('in_transit','delivered')),
  add column acceptance text check (acceptance in ('accepted','rejected')),
  add column grn_number text,
  add column pod_path text,
  add column closure_status text not null default 'pending'
    check (closure_status in ('pending','closed')),
  add column remarks text;

-- ---------------------------------------------------------------------------
-- Commission (only after the OEM-payment milestone)
-- ---------------------------------------------------------------------------

create table public.commission_invoices (
  id uuid primary key default gen_random_uuid(),
  commission_no text not null unique,
  oem_invoice_id uuid not null references public.oem_invoices(id),
  oem_id uuid not null references public.oems(id),
  customer_id uuid references public.customers(id),
  commission_pct numeric(6,2) not null check (commission_pct >= 0),
  base_amount numeric(14,2) not null check (base_amount >= 0),
  commission_amount numeric(14,2) not null check (commission_amount >= 0),
  gst_amount numeric(14,2) not null default 0,
  gross_value numeric(14,2) not null default 0,
  invoice_date date not null,
  due_date date,
  payment_status text not null default 'pending'
    check (payment_status in ('pending','paid')),
  received_on date,
  tds_deducted boolean not null default false,
  outstanding_amount numeric(14,2),
  attachment_path text,
  remarks text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

-- The milestone rule, made structural: a commission invoice needs a real payment on its OEM invoice.
create or replace function public.check_commission_milestone()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1 from public.payments
    where oem_invoice_id = new.oem_invoice_id
  ) then
    raise exception 'Commission cannot be raised before the OEM-payment milestone (invoice %)',
      new.oem_invoice_id;
  end if;
  return new;
end;
$$;

create trigger commission_milestone
  before insert or update on public.commission_invoices
  for each row execute function public.check_commission_milestone();

-- ---------------------------------------------------------------------------
-- Audit + RLS for the new tables
-- ---------------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array[
    'customers','customer_contacts','products','product_oems','order_lines',
    'material_readiness','commission_invoices'
  ] loop
    execute format('alter table public.%1$I enable row level security', t);
    execute format(
      'create policy owner_all on public.%1$I for all
       using (public.is_owner()) with check (public.is_owner())', t);
    execute format(
      'create trigger audit_%1$s after insert or update or delete on public.%1$I
       for each row execute function public.write_audit()', t);
  end loop;
end $$;

create index order_lines_order_idx on public.order_lines(order_id);
create index material_readiness_order_idx on public.material_readiness(order_id);
create index oem_invoices_order_idx on public.oem_invoices(order_id);
create index payments_oem_invoice_idx on public.payments(oem_invoice_id);
create index commission_oem_invoice_idx on public.commission_invoices(oem_invoice_id);
create index products_part_idx on public.products using gin (part_number gin_trgm_ops);

-- ==================== supabase/migrations/0006_profiles_on_signup.sql ====================
-- 0006_profiles_on_signup.sql — give every new auth user a profiles row (and therefore a role).
-- Why: 0004's RLS policies call current_app_role(), which reads profiles. A signed-in user with
-- no profile row has role NULL, so every policy denies. This trigger closes that trap.
-- Apply in the SQL editor AFTER 0001-0005, and BEFORE creating the user (so the trigger fires).
-- STATUS: written, not yet applied.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    coalesce(nullif(new.raw_user_meta_data ->> 'role', '')::public.app_role, 'owner')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- The role defaults to 'owner' (Ram is the principal). Change it deliberately for other users:
--   update public.profiles set role = 'sales' where id = '<user-uuid>';
--
-- If you already created a user BEFORE applying this migration, add their profile by hand:
--   insert into public.profiles (id, full_name, role)
--   select id, email, 'owner' from auth.users where email = '<your-email>'
--   on conflict (id) do nothing;

-- ==================== supabase/migrations/0007_quote_line_pricing.sql ====================
-- 0007_quote_line_pricing.sql — expose the recommended price on quote lines, computed in SQL.
-- Why: the pricing rule must live once, in SQL (docs/TECH-STACK.md), not be recomputed in the app.
-- recommended_price() is IMMUTABLE, so it can back a generated column.
-- Apply in the SQL editor after 0001-0006. STATUS: written, not yet applied.

alter table public.quote_version_lines
  add column if not exists recommended_price numeric(14,2)
  generated always as (public.recommended_price(oem_price, target_margin_pct)) stored;

-- Check: select oem_price, target_margin_pct, recommended_price from public.quote_version_lines limit 5;

-- ==================== supabase/migrations/0008_create_requirement.sql ====================
-- 0008_create_requirement.sql — create a requirement and its lines atomically.
-- Why a function: the header plus lines must save together or not at all. Two REST calls can
-- leave a header with no lines if the second fails; one function is one transaction.
-- SECURITY INVOKER (the default) means RLS applies to the caller, so a user who cannot insert
-- requirements cannot insert them through this function either.
-- Apply in the SQL editor after 0001-0007. STATUS: written, not yet applied.

create or replace function public.create_requirement_with_lines(
  p_ref text,
  p_customer text,
  p_status public.requirement_status,
  p_submission_deadline date,
  p_lines jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_id uuid;
  v_line jsonb;
  v_no integer := 0;
begin
  if p_lines is null or jsonb_array_length(p_lines) = 0 then
    raise exception 'A requirement needs at least one line item';
  end if;

  insert into public.requirements (ref, customer, status, submission_deadline, is_demo)
  values (p_ref, p_customer, p_status, p_submission_deadline, false)
  returning id into v_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_no := v_no + 1;
    insert into public.requirement_lines
      (requirement_id, line_no, part_number, description, quantity, uom, deadline, is_demo)
    values (
      v_id,
      v_no,
      v_line ->> 'part_number',
      coalesce(v_line ->> 'description', ''),
      (v_line ->> 'quantity')::integer,
      v_line ->> 'uom',
      (v_line ->> 'deadline')::date,
      false
    );
  end loop;

  return v_id;
end;
$$;

-- ==================== supabase/migrations/0009_create_order_from_quote.sql ====================
-- 0009_create_order_from_quote.sql — turn an APPROVED quote into an order and its lines, atomically.
-- The "no orphan PO" rule: only an approved quote can become an order. The orders trigger
-- enforces it too, but this gives a clear message and copies the lines in one transaction.
-- SECURITY INVOKER: RLS applies to the caller.
-- Apply in the SQL editor after 0001-0008. STATUS: written, not yet applied.

create or replace function public.create_order_from_quote(
  p_quote_id uuid,
  p_po_number text,
  p_po_date date,
  p_po_value numeric
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_quote public.quotes;
  v_order_id uuid;
begin
  select * into v_quote from public.quotes where id = p_quote_id;
  if v_quote.id is null then
    raise exception 'Quote % not found', p_quote_id;
  end if;
  if v_quote.status <> 'approved' then
    raise exception 'Only an approved quote can become an order (this quote is %)', v_quote.status;
  end if;

  if exists (
    select 1
    from public.quote_versions qv
    join public.quote_version_lines qvl on qvl.quote_version_id = qv.id
    where qv.quote_id = p_quote_id
      and qv.version_no = v_quote.current_version
      and qvl.final_price is null
  ) then
    raise exception 'Every quote line needs a final price before an order can be created';
  end if;

  insert into public.orders
    (quote_id, requirement_id, po_number, po_date, po_value, status,
     partial_allowed, pdi_required, is_demo)
  values
    (p_quote_id, v_quote.requirement_id, p_po_number, p_po_date, p_po_value, 'processing',
     true, true, false)
  returning id into v_order_id;

  insert into public.order_lines
    (order_id, requirement_line_id, part_number, quantity_ordered, unit_price, is_demo)
  select v_order_id, qvl.requirement_line_id, rl.part_number, rl.quantity, qvl.final_price, false
  from public.quote_versions qv
  join public.quote_version_lines qvl on qvl.quote_version_id = qv.id
  join public.requirement_lines rl on rl.id = qvl.requirement_line_id
  where qv.quote_id = p_quote_id and qv.version_no = v_quote.current_version;

  if not exists (select 1 from public.order_lines where order_id = v_order_id) then
    raise exception 'The approved quote has no line items to order';
  end if;

  return v_order_id;
end;
$$;

-- ==================== supabase/migrations/0010_raise_commission.sql ====================
-- 0010_raise_commission.sql — raise a commission invoice from an OEM invoice.
-- The commission percentage and GST are applied in SQL, so the money figure is computed in one
-- place. The check_commission_milestone trigger (0005) already forbids a commission invoice
-- before an OEM payment exists; this function adds a clearer message and computes the amounts.
-- SECURITY INVOKER: RLS applies to the caller.
-- NOTE: the commission rule is assumption A5, not client-confirmed. Implemented as stated.
-- Apply in the SQL editor after 0001-0009. STATUS: written, not yet applied.

create or replace function public.raise_commission_invoice(
  p_oem_invoice_id uuid,
  p_commission_no text,
  p_commission_pct numeric,
  p_invoice_date date
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_invoice public.oem_invoices;
  v_base numeric;
  v_commission numeric;
  v_gst numeric;
  v_gross numeric;
  v_id uuid;
begin
  select * into v_invoice from public.oem_invoices where id = p_oem_invoice_id;
  if v_invoice.id is null then
    raise exception 'OEM invoice % not found', p_oem_invoice_id;
  end if;
  if v_invoice.oem_id is null then
    raise exception 'The OEM invoice has no OEM, so a commission cannot be raised against it';
  end if;
  if not exists (select 1 from public.payments where oem_invoice_id = p_oem_invoice_id) then
    raise exception 'Commission cannot be raised before the OEM-payment milestone is met';
  end if;
  if p_commission_pct is null or p_commission_pct < 0 then
    raise exception 'Commission percentage must be zero or greater';
  end if;

  v_base := coalesce(v_invoice.gross_amount, 0);
  v_commission := round(v_base * p_commission_pct / 100.0, 2);
  v_gst := round(v_commission * 0.18, 2);
  v_gross := v_commission + v_gst;

  insert into public.commission_invoices
    (commission_no, oem_invoice_id, oem_id, commission_pct, base_amount, commission_amount,
     gst_amount, gross_value, invoice_date, payment_status, outstanding_amount, is_demo)
  values
    (p_commission_no, p_oem_invoice_id, v_invoice.oem_id, p_commission_pct, v_base, v_commission,
     v_gst, v_gross, p_invoice_date, 'pending', v_gross, false)
  returning id into v_id;

  return v_id;
end;
$$;

-- ==================== supabase/migrations/0011_followup_tasks.sql ====================
-- 0011_followup_tasks.sql — the follow-up reminder queue.
-- A re-runnable generator that turns stale records into tasks. Idempotent: every task carries a
-- dedupe_key with a unique index, so running it twice does not duplicate a task.
-- SECURITY INVOKER: RLS applies to the caller. If run by pg_cron it runs privileged, which is fine.
-- Apply in the SQL editor after 0001-0010. STATUS: written, not yet applied.

alter table public.tasks add column if not exists dedupe_key text;
create unique index if not exists tasks_dedupe_key_idx on public.tasks(dedupe_key);

create or replace function public.generate_followup_tasks()
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_count integer := 0;
  v_rows integer;
begin
  -- Quotes silent for 7 days
  insert into public.tasks (kind, title, owner_type, owner_id, due_date, dedupe_key, is_demo)
  select 'quote_followup',
         'Chase quote ' || coalesce(r.ref, q.id::text),
         'quote', q.id, current_date, 'quote:' || q.id || ':7d', false
  from public.quotes q
  join public.requirements r on r.id = q.requirement_id
  where q.status in ('draft', 'pending_approval')
    and q.created_at <= now() - interval '7 days'
  on conflict (dedupe_key) do nothing;
  get diagnostics v_rows = row_count;
  v_count := v_count + v_rows;

  -- OEM requests with no response for 7 days
  insert into public.tasks (kind, title, owner_type, owner_id, due_date, dedupe_key, is_demo)
  select 'oem_followup',
         'Chase OEM response (' || o.name || ')',
         'oem_request', req.id, current_date, 'oemreq:' || req.id, false
  from public.oem_requests req
  join public.oems o on o.id = req.oem_id
  where req.responded_at is null
    and req.requested_at <= now() - interval '7 days'
  on conflict (dedupe_key) do nothing;
  get diagnostics v_rows = row_count;
  v_count := v_count + v_rows;

  -- Invoices due within 7 days with an outstanding balance
  insert into public.tasks (kind, title, owner_type, owner_id, due_date, dedupe_key, is_demo)
  select 'payment_due',
         'Payment due on ' || i.invoice_no,
         'oem_invoice', i.id, i.due_date, 'invoice:' || i.id || ':' || i.due_date, false
  from public.oem_invoices i
  where i.due_date is not null
    and i.due_date <= current_date + 7
    and i.gross_amount > coalesce(
      (select sum(p.amount) from public.payments p where p.oem_invoice_id = i.id), 0)
  on conflict (dedupe_key) do nothing;
  get diagnostics v_rows = row_count;
  v_count := v_count + v_rows;

  -- Documents expiring within 60 days (or already expired)
  insert into public.tasks (kind, title, owner_type, owner_id, due_date, dedupe_key, is_demo)
  select 'document_expiry',
         'Document expiring: ' || d.title,
         'document', d.id, d.expiry_date, 'doc:' || d.id || ':' || d.expiry_date, false
  from public.documents d
  where d.expiry_date is not null
    and d.expiry_date <= current_date + 60
  on conflict (dedupe_key) do nothing;
  get diagnostics v_rows = row_count;
  v_count := v_count + v_rows;

  return v_count;
end;
$$;

-- To run it on a schedule, enable the pg_cron extension (Dashboard -> Database -> Extensions),
-- then run once:
--   select cron.schedule('generate-followups', '0 6 * * *',
--                        $$select public.generate_followup_tasks();$$);
-- and check with: select * from cron.job;

-- ==================== supabase/migrations/0012_update_requirement.sql ====================
-- 0012_update_requirement.sql — edit a requirement header and its lines in one transaction.
-- Existing lines are updated in place (by id); new lines (no id) are appended. Deleting a line is
-- deliberately not offered yet, because commitments and quote lines reference line ids.
-- SECURITY INVOKER: RLS applies to the caller.
-- Apply in the SQL editor after 0001-0011. STATUS: written, not yet applied.

create or replace function public.update_requirement_with_lines(
  p_id uuid,
  p_ref text,
  p_customer text,
  p_status public.requirement_status,
  p_submission_deadline date,
  p_loss_reason public.loss_reason,
  p_notes text,
  p_lines jsonb
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_line jsonb;
  v_no integer;
begin
  update public.requirements
     set ref = p_ref,
         customer = p_customer,
         status = p_status,
         submission_deadline = p_submission_deadline,
         loss_reason = p_loss_reason,
         notes = p_notes
   where id = p_id;
  if not found then
    raise exception 'Requirement % not found', p_id;
  end if;

  if p_lines is null or jsonb_array_length(p_lines) = 0 then
    raise exception 'A requirement needs at least one line item';
  end if;

  select coalesce(max(line_no), 0) into v_no
  from public.requirement_lines where requirement_id = p_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    if (v_line ->> 'id') is not null and (v_line ->> 'id') <> '' then
      update public.requirement_lines
         set part_number = v_line ->> 'part_number',
             description = coalesce(v_line ->> 'description', ''),
             quantity = (v_line ->> 'quantity')::integer,
             uom = v_line ->> 'uom',
             deadline = (v_line ->> 'deadline')::date
       where id = (v_line ->> 'id')::uuid and requirement_id = p_id;
      if not found then
        raise exception 'Line % does not belong to this requirement', v_line ->> 'id';
      end if;
    else
      v_no := v_no + 1;
      insert into public.requirement_lines
        (requirement_id, line_no, part_number, description, quantity, uom, deadline, is_demo)
      values (
        p_id, v_no, v_line ->> 'part_number', coalesce(v_line ->> 'description', ''),
        (v_line ->> 'quantity')::integer, v_line ->> 'uom', (v_line ->> 'deadline')::date, false
      );
    end if;
  end loop;
end;
$$;

-- ==================== supabase/migrations/0013_add_commitment.sql ====================
-- 0013_add_commitment.sql — record a firm or indicative OEM commitment against a line.
-- Computes the next shipment sequence for the (line, OEM) pair so multiple shipments do not
-- collide. The coverage view reads these rows, so coverage updates immediately.
-- SECURITY INVOKER: RLS applies to the caller.
-- Apply in the SQL editor after 0001-0012. STATUS: written, not yet applied.

create or replace function public.add_commitment(
  p_requirement_line_id uuid,
  p_oem_id uuid,
  p_kind public.commitment_kind,
  p_quantity integer,
  p_unit_price numeric,
  p_expected_date date
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_seq integer;
  v_id uuid;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Commitment quantity must be greater than zero';
  end if;

  select coalesce(max(shipment_seq), 0) + 1 into v_seq
  from public.commitments
  where requirement_line_id = p_requirement_line_id and oem_id = p_oem_id;

  insert into public.commitments
    (requirement_line_id, oem_id, kind, quantity, unit_price, expected_date, shipment_seq, is_demo)
  values
    (p_requirement_line_id, p_oem_id, p_kind, p_quantity, p_unit_price, p_expected_date, v_seq, false)
  returning id into v_id;

  return v_id;
end;
$$;

-- ==================== supabase/migrations/0014_quote_lifecycle.sql ====================
-- 0014_quote_lifecycle.sql — create a draft quote from a requirement, and approve a quote.
-- Price source: the cheapest firm commitment on the line, else the cheapest OEM product price,
-- else 0; the recommended price is generated from it (0007) and the final price stays human.
-- SECURITY INVOKER: RLS applies to the caller.
-- Apply in the SQL editor after 0001-0013. STATUS: written, not yet applied.

create or replace function public.create_quote_for_requirement(
  p_requirement_id uuid,
  p_margin_pct numeric default 15
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_quote uuid;
  v_version uuid;
begin
  if not exists (select 1 from public.requirements where id = p_requirement_id) then
    raise exception 'Requirement % not found', p_requirement_id;
  end if;
  if not exists (select 1 from public.requirement_lines where requirement_id = p_requirement_id) then
    raise exception 'The requirement has no line items to quote';
  end if;

  insert into public.quotes (requirement_id, status, current_version, is_demo)
  values (p_requirement_id, 'draft', 1, false)
  returning id into v_quote;

  insert into public.quote_versions (quote_id, version_no, status, is_demo)
  values (v_quote, 1, 'draft', false)
  returning id into v_version;

  insert into public.quote_version_lines
    (quote_version_id, requirement_line_id, oem_price, lead_time_days, target_margin_pct, is_demo)
  select
    v_version,
    l.id,
    coalesce(
      (select min(c.unit_price) from public.commitments c
        where c.requirement_line_id = l.id and c.kind = 'firm'),
      (select min(op.unit_price) from public.oem_products op where op.part_number = l.part_number),
      0
    ),
    coalesce(
      (select min(op.lead_time_days) from public.oem_products op where op.part_number = l.part_number),
      0
    ),
    p_margin_pct,
    false
  from public.requirement_lines l
  where l.requirement_id = p_requirement_id;

  update public.requirements set status = 'quoted' where id = p_requirement_id and status = 'received';

  return v_quote;
end;
$$;

create or replace function public.approve_quote(p_quote_id uuid)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_version integer;
begin
  select current_version into v_version from public.quotes where id = p_quote_id;
  if v_version is null then
    raise exception 'Quote % not found', p_quote_id;
  end if;

  update public.quotes set status = 'approved' where id = p_quote_id;
  update public.quote_versions
     set status = 'approved', approved_at = now()
   where quote_id = p_quote_id and version_no = v_version;
end;
$$;

-- ==================== supabase/migrations/0015_oem_capacity.sql ====================
-- 0015_oem_capacity.sql — A1: OEM capacity as explicit data plus a configuration flag.
-- A1 (docs/ASSUMPTIONS.md): capacity is a GLOBAL pool — available = declared − all firm commitments.
-- If Ram overturns that, it is a flag, not a rewrite: `oems.capacity_shared` says whether capacity
-- is shared across all orders (global) or separate to each order.
-- Declared capacity is per OEM product; `available` and `over_committed` are derived here, never
-- stored. Products with no declared capacity report NULL available (unknown) and are never flagged.
-- SECURITY INVOKER: RLS applies to the caller.
-- Apply in the SQL editor after 0001-0014. STATUS: written, not yet applied.

alter table public.oem_products
  add column if not exists declared_capacity integer
  check (declared_capacity is null or declared_capacity >= 0);

alter table public.oems
  add column if not exists capacity_shared boolean not null default true;

create or replace view public.oem_product_capacity
with (security_invoker = true) as
select
  op.id as oem_product_id,
  op.oem_id,
  op.part_number,
  op.declared_capacity,
  coalesce(sum(c.quantity) filter (where rl.id is not null), 0)::int as firm_committed,
  case
    when op.declared_capacity is null then null
    else greatest(
      op.declared_capacity - coalesce(sum(c.quantity) filter (where rl.id is not null), 0), 0
    )::int
  end as available,
  case
    when op.declared_capacity is null then 0
    else greatest(
      coalesce(sum(c.quantity) filter (where rl.id is not null), 0) - op.declared_capacity, 0
    )::int
  end as over_committed
from public.oem_products op
left join public.commitments c
  on c.oem_id = op.oem_id and c.kind = 'firm'
left join public.requirement_lines rl
  on rl.id = c.requirement_line_id and rl.part_number = op.part_number
group by op.id, op.oem_id, op.part_number, op.declared_capacity;

-- ==================== supabase/migrations/0016_leads.sql ====================
-- 0016_leads.sql — the front of the funnel: a lead captured from a call, WhatsApp or referral.
-- A lead is a pre-RFI opportunity. When it matures it converts to a requirement (the tender system).
-- Apply in the SQL editor after 0001-0015. STATUS: written, not yet applied.

create type lead_source as enum
  ('call','whatsapp','referral','gem','portal','direct','other');
create type lead_stage as enum
  ('new','contacted','qualified','quoted','won','lost');

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  source lead_source not null default 'call',
  name text not null,
  company text,
  phone text,
  email text,
  product_note text,
  stage lead_stage not null default 'new',
  next_follow_up date,
  owner text,
  converted_requirement_id uuid references public.requirements(id),
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create index leads_followup_idx on public.leads(next_follow_up);
create index leads_stage_idx on public.leads(stage);

alter table public.leads enable row level security;

create policy owner_all on public.leads
  for all using (public.is_owner()) with check (public.is_owner());

create policy sales_rw on public.leads
  for all using (public.current_app_role() = 'sales')
  with check (public.current_app_role() = 'sales');

create trigger audit_leads
  after insert or update or delete on public.leads
  for each row execute function public.write_audit();

