-- ============================================================================
-- 005 — seed quotes (with versions and lines) and documents.
-- Run AFTER 003 (requirements) and 004 (lines). Requires migration 0007 (recommended_price).
-- Safe to re-run.
-- ============================================================================

-- Quotes
insert into public.quotes (requirement_id, status, current_version, is_demo, created_at)
select r.id, v.status::quote_status, v.current_version, true, v.created_at::timestamptz
from (values
  ('RFI-2026-001','approved',2,'2026-08-06'),
  ('RFI-2026-003','draft',1,'2026-09-05'),
  ('RFI-2026-007','approved',1,'2026-09-02'),
  ('RFI-2026-011','pending_approval',1,'2026-09-20')
) as v(ref, status, current_version, created_at)
join public.requirements r on r.ref = v.ref
where not exists (select 1 from public.quotes q where q.requirement_id = r.id);

-- Quote versions
insert into public.quote_versions (quote_id, version_no, status, approved_at, is_demo)
select q.id, v.version_no, v.status::quote_status, nullif(v.approved_at, '')::timestamptz, true
from (values
  ('RFI-2026-001',1,'superseded','2026-08-06'),
  ('RFI-2026-001',2,'approved','2026-08-09'),
  ('RFI-2026-003',1,'draft',''),
  ('RFI-2026-007',1,'approved','2026-09-03'),
  ('RFI-2026-011',1,'pending_approval','')
) as v(ref, version_no, status, approved_at)
join public.requirements r on r.ref = v.ref
join public.quotes q on q.requirement_id = r.id
on conflict (quote_id, version_no) do nothing;

-- Quote version lines (recommended_price is generated by 0007, so it is not inserted)
insert into public.quote_version_lines
  (quote_version_id, requirement_line_id, oem_price, lead_time_days, target_margin_pct, final_price, is_demo)
select qv.id, l.id, v.oem_price, v.lead_time_days, 15, nullif(v.final_price, '')::numeric, true
from (values
  ('RFI-2026-001',2,1,42000,45,'48300'),
  ('RFI-2026-001',2,2,3500,30,'4025'),
  ('RFI-2026-003',1,1,51000,60,''),
  ('RFI-2026-003',1,2,7800,25,''),
  ('RFI-2026-007',1,1,6400,20,'7360'),
  ('RFI-2026-011',1,1,49500,45,'')
) as v(ref, version_no, line_no, oem_price, lead_time_days, final_price)
join public.requirements r on r.ref = v.ref
join public.quotes q on q.requirement_id = r.id
join public.quote_versions qv on qv.quote_id = q.id and qv.version_no = v.version_no
join public.requirement_lines l on l.requirement_id = r.id and l.line_no = v.line_no
on conflict (quote_version_id, requirement_line_id) do nothing;

-- Documents (compliance certificates for OEMs, one quotation for a requirement)
insert into public.documents (type, owner_type, owner_id, title, issue_date, expiry_date, is_demo)
select v.type::document_type, v.owner_type, o.id, v.title,
       nullif(v.issue_date, '')::date, nullif(v.expiry_date, '')::date, true
from (values
  ('compliance_certificate','oem','OEM A','OEM A compliance certificate','2026-06-01','2026-11-15'),
  ('compliance_certificate','oem','OEM B','OEM B compliance certificate','2026-06-01','2027-06-01'),
  ('compliance_certificate','oem','OEM C','OEM C compliance certificate','2024-09-01','2026-09-01')
) as v(type, owner_type, owner_name, title, issue_date, expiry_date)
join public.oems o on o.name = v.owner_name
where not exists (select 1 from public.documents d where d.title = v.title);

insert into public.documents (type, owner_type, owner_id, title, issue_date, expiry_date, is_demo)
select 'quotation'::document_type, 'requirement', r.id, 'Quotation ' || r.ref || ' v2',
       '2026-08-09'::date, null, true
from public.requirements r
where r.ref = 'RFI-2026-001'
  and not exists (select 1 from public.documents d where d.title = 'Quotation RFI-2026-001 v2');
